### ISSUE TITLE
Unable to push commit to github

### ISSUE THREAD

**Issue by sirnewton01** [driusan/go-git#2] opened 2016-12-08 03:56 UTC
Clone a simple project (sirnewton01/p9-tutorial) onto my local system. Make a small modification to one of the text files. Add it and commit it with a message. Change .git/config to add the following line.

[branch "master"]
    remote = origin
>>>    merge = refs/heads/master

Run 'go-git push master' and authenticate against github to push the change.

The flow gets all of the way to retrieve.go SendPack(). The HTTP request goes out to github and the response is 200 OK, but nothing seems to happen on github.

**Comment by driusan** [comment] 2016-12-08 12:43
Seems like a regression.. I have a feeling I accidentally did a go-git push which is implicitly a force push which overwrote the fix. I'll take a look and try to reproduce.

(200 OK means nothing in the git protocol other than that the server got your request.)

**Comment by driusan** [comment] 2016-12-08 14:53
Can you double check that PR #3 fixes this? I was able to clone your repo, make a small change, and push it all using go-git on a Mac.

**Comment by sirnewton01** [comment] 2016-12-09 02:14
I gave it a try again with the latest in this repository, but I'm hitting a couple of other problems with clone. There are compile errors in hash object.go (easy to fix, unused variables). The next problem is with a bad head pointer. The code is expected .git/HEAD to be something like ref: refs/head/master, but in my case during the clone it is a commit id. I tried correcting it but then it complains that there is no .git/index.

To reproduce, try the following:
go-git clone https://github.com/sirnewton01/p9-tutorial

**Comment by driusan** [comment] 2016-12-09 03:05
The compile errors should already be fixed.. I'm not sure how go-git clone is getting into a detached head state since go-git doesn't know anything about detached heads.

I can reproduce it, so I'll look into it and see what's going on. As a temporary workaround, you can fix it to `ref: refs/heads/master`, and then do a `go-get reset HEAD --hard` to create the index and reset the working directory.

**Comment by driusan** [comment] 2016-12-09 03:12
1ce35495180c5fb6912e32cc8d96b5e1cbcf8ae0 should fix the problem with HEAD not being set as expected while cloning.

**Comment by sirnewton01** [comment] 2016-12-09 04:26
Thanks, I can clone now without any problems. I tried adding/committing/pushing a simple mod to a file. The effect is that same as last time in that github doesn't get updated with the new commit. However, there appear to be error messages this time.

<img width="738" alt="screen shot 2016-12-08 at 11 25 53 pm" src="https://cloud.githubusercontent.com/assets/3670311/21037678/be55772c-bd9d-11e6-8a74-b4b1f2d82cc6.png">

**Comment by driusan** [comment] 2016-12-09 12:56
Ok, that's some kind of progress. It means we're sending a valid packfile which the server is able to process, but "missing necessary objects" suggests that the packfile doesn't contain all the objects it's supposed to. That line should be "0019ok refs/heads/master". I just tried a simple push to a fork of p9-tutorial and it seemed to work on this machine (DragonflyBSD), suggesting it's either something specific to Plan 9, or specific to the change.

What happens if you run go-git rev-list --objects $localsha1 ^$remotesha1
where local and remotesha1 are the complete hashes snarf/pasted from your screenshot?

It should print approximately 3 lines (one for the new commit, one for the hash of the new file, and one for the hash of the directory with the new file's contents.) Each of them should have a file in .git/objects/x/y where x is the first byte of the hash in hex, and y is the remaining 19 bytes in hex.

**Comment by sirnewton01** [comment] 2016-12-10 03:09
Sorry for the wait. I tried the go-git rev-list command and received a panic. "/usr/glenda/p9-tutorial/.git/packed-refs does not exist." The stack trace reveals the problem to be at rev-list.go line 59.

**Comment by driusan** [comment] 2016-12-10 14:42
That line is just panicing on any error returned by RevParse, and the only path I can see which returns an error is if it can't find a branch, which isn't supposed to happen until after the part that handles SHA1 hashes that aren't branches in rev-parse.

Around line 53 in revparse.go can you print:  1. len(sha) 2. The value of sha and see why it's not getting into the if statement? I suspect you're using an abbreviated hash (which isn't supported yet)

(Of course, that doesn't explain the underlying problem of the push not working..)

**Comment by sirnewton01** [comment] 2016-12-10 19:26
Yeah, sorry I was putting in the abbreviations. I outputted the sizes of the two hashes and initially, I was getting 80. Then I realized that rc shell uses '^' character to append two strings. I tried the rev-list command again with single quotes around the hashes and the carat. This time I get 40 and 40 and no other output at all. So, just this

%term go-git rev-list ...
40
40

As another data point, I tried running go-git status and now it seems that every file in the sandbox is a new file and is staged, ready for commit. I'm not sure if this is another problem or related to this one.

Thanks,
Chris

**Comment by driusan** [comment] 2016-12-11 00:39
Hard to say if it's related or not at this point. It's definitely not because of the '^' character in rc though, because go-git directly calls the RevList() method from Go when doing a push, not through a shell. Are you sure you got them in the right order? `git rev-list a ^b` means "print all commits reachable from a that aren't reachable from b", so if they were backwards the empty set would make sense. `(go-)git push` runs that command (with `--objects` as a parameter, to also print the tree and blob objects) to figure out what objects it needs to send in the packfile that it sends to the server. If it's RevList is returning nothing, it explains why the server is getting a packfile with nothing in it and complaining that it's missing objects.

The status thing could be either the index is corrupted, or the c.GitDir directory or c.WorkTree is wrong (or can't be accessed for some reason). I think the GitDir being wrong makes the most sense, because it could explain both problems.

You can print `c.GitDir.String()` (from pretty much any method that gets called (you might also want to print `repo.Path`. It's the equivalent of c.GitDir for the third party git library that I'm trying to get away with, but still gets used here and there because I haven't reimplemented everything that it does yet.) to make sure it's accurate. You can also try running with --git-dir (before the "rev-list") to force it to be set and see if that helps.

The `RevList()` code isn't the best in the world, but signs seem to be pointing towards something being wrong there, so you might want to hack it up with some debug statements to see where it's going wrong.

**Comment by sirnewton01** [comment] 2016-12-11 04:11
I appreciate your help with this. If this thread of discussion is helpful (and not a distraction) then I will keep going with it. Otherwise, I can try to spend more time trying to understand the code (and the git protocol) and see if I can solve the problems directly and give pull requests.

I tried reversing the two commits as you suggested and the output to rev-list appears to be every commit in the repository. I outputted both the c.GitDir.String() and the repo.Path and they both appear to point to the .git directory in the git repo that I'm currently working on. Nothing strange there.

Is it possible that when I'm doing a push somehow the locate and remote commits get reversed and then it decides that there are no packs that need to be sent to the server? When I originally formatted my git rev-list as you suggested, I took the local and remote commits using the template your provided with the output from the push, of this form:

Refname: refs/head/master Remote sha1: <REMOTE HASH> Local sha1: <LOCAL HASH>

When I did that it returned nothing. When I flip the two I'm getting every commit.

**Comment by driusan** [comment] 2016-12-11 14:47
I don't mind helping debug, since I know the code and I'd like to get it working.

If you want to dig into it more yourself, the general flow of go-git push is:
1. Look up the url of the branch being pushed, and the refspec in the .git/gitconfig file
2. Use the git pack protocol to fetch a list of revisions from that url (the pack protocol is documented with the git technical documentation [here](https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt) and the HTTP variant [here](https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt), parse the response into what the server has for each refspec (this is the step that NegotiateSendPack does.) The most likely thing to go wrong at this point is that the parsing goes wrong because the first line has a `\0` at the end of the refspec while the other lines have a `\n`. (But if that were the problem, I don't think you would have gotten the remote/local sha1 line because the remote would have been miscalculated, unless there's a non-printable character hidden in that message.. but then one of them wouldn't have had a length of 40.)
3. Iterate through the remote refspecs to see if any of them match the branch we're trying to push according to what we got out of the config.
4. Call RevList() (essentially the same function as `go-git rev-list --objects`) to find a list of commits (and their objects) missing from the server. I think this is where it's going wrong.
5. Call PackObjects() (the same function as `go-git pack-objects`) and send it the list of objects to create a packfile with the objects that are missing from the server, and send the packfile to the server with a line in the pack protocol telling it to update the remote ref to the new commit.

It definitely seems like either something's corrupt in your .git directory, or something's going wrong in step 4. (If it was step 5 you wouldn't get a packfile ok response from the server, and if it were 1-3 you wouldn't get the debug line printing the local/remote sha1.)

I can't think of any way that the commits would be getting reversed in your code, because then the same problems would happen when I try and push from MacOS or DflyBSD. Are you on ARM or x86? (Maybe it's an endian issue?)

If you email me an archive (zip, tar, whatever) of your `.git` directory to see if I can poke around with it with the official git client and see if I get the same rev-list or if something looks corrupted.

**Comment by sirnewton01** [comment] 2016-12-12 02:43
I started from a clean clone and copied the git repository to my mac through the steps of modifying a file, getting a status, adding the file to the staging area and committing. Git status did not report any errors until after I committed. At that point I get the following error on my regular Git client.

error: bogus commit object b8e2d79558b8ee533a6f8d87bc1e84abf8e60b4a
fatal: bad object HEAD

The error seems to come from here in the official git client source:
https://github.com/git/git/blob/master/commit.c#L330

It seems that the commit operation corrupts the repo. I don't think it is an endianness problem since I'm running this on 386, which would be the same endianness as on MacOS.

Here's a hex dump of the bogus commit:

0000000  789c9ccd c18dc320 1000c07b 53c53670
0000010  271683e1 a4d32951 1e79a586 688dd786
0000020  87590be3 58e93e8f 74900246 13655972
0000030  0383dd57 abcca056 aa5c1a30 eade0713
0000040  b09f38d8 888c817a ed3da277 ec269ecc
0000050  60adfdb5 8af696a4 c225d5bc c12d5e99
0000060  e16fcbb5 f0d1a4dc 359e9e94 447e22fd
0000070  03da80ce 78ef3bf8 d64e6bf5 ce1b7fc8
0000080  d5791c61 a54a73a5 35010db2 3758e491
0000090  cb0c472e a31c9b7a 050000ff ffc40445
00000a0  2e000000
00000a1

**Comment by driusan** [comment] 2016-12-12 15:09
That's weird, I use go-git commit all the time on Mac (I force myself to type the extra three characters so that I'll catch any regressions..). But git is right: that's not a valid commit object. Git objects are zlib compressed streams of text of the form `<type><SP><size>\0<data>`, stored in a file named after the sha1 of `<data>` this is what that zlib stream decompresses to: https://play.golang.org/p/BUgJQpO1Oo

A valid commit should look like this (without the type/size part):

```sh
$ git cat -t commit HEAD
> git cat-file -p HEAD
tree e3ab954e4d383119ad7cdff4018a1d63b52520d3
parent 1556052a02abe8eed2c4e62501c76fa44b20a791
author Dave MacFarlane <david.macfarlane2@mcgill.ca> 1481208542 -0500
committer Dave MacFarlane <david.macfarlane2@mcgill.ca> 1481208556 -0500

Added merge attribute to branch on clone
```

So the tree is clearly not getting writing properly to the commit object in your system.

Commit calls WriteTree to write the tree object to `.git/objects`, then CommitTree to write the commit object, then updates the HEAD pointer.

The first thing to do: compare `go-git write-tree` and `git write-tree` on your Mac. They should both print the same hash to your screen.

commit-tree is a little harder to test because the commit object includes the timestamp so the hash will be different, but the problem seems to be somewhere before the "// TODO: Validate tree id" comment in committree.go. Try adding a panic `if tree == ""` statement (in fact, you can probably go one further and panic `if len(tree.String()) != 40`, because it should be the complete hash before it gets written.), then you can work backwards from there.

**Comment by sirnewton01** [comment] 2016-12-14 03:29
I seem to have figured out the problem(s). It was in the writing of the tree. The sha1 of the tree coming back was empty because there was an internal error writing the tree. The error was never shown, but it had to do with creating the two digit directory to store the tree object.

There is code to write out the zlib compressed object in the driusan/git repository. Blob.go StoreObjectLoose writes a temporary file with a prefix ".gogit_" so that it can calculate the sha1 hash of the contents. Once it has the sha1 hash it figures out the first two characters that form the directory where the file will eventually be stored. The call to os.Mkdir() fails in my case because the directory already exists (not sure why, but it is quite possible that it could exist because another hash has the same first two letters).

This is probably a Go bug on Plan 9, but the error returned from os.Mkdir() because the directory already exists does not pass the os.IsExist() check. An alternative could be to try os.Open() + os.Stat() to see if it exists before calling os.Mkdir(). In theory, this could be a good way to detect the highly unusual case where there is a file, not directory, already there with the same name. I'm not sure how far you want to go to work around what seems to be a Go bug for the sake of detecting a highly unlikely corruption.

After working around the os.Mkdir() bug, there is a problem with the os.Rename(). On Plan 9, it seems that the rename is not able to move files between directories, which is what is happening here. The file is being moved out from the objects directory into a two-letter directory underneath. In this case Go actually does warn against using rename to move files between directories as "OS-specific restrictions may apply when oldpath and newpath are in different directories." I know that Plan 9 is a bit quirky when it comes to moving files even on the command-line.

Instead of a rename, I tried copy the contents between the two files (original, and new) using a io.Copy() and then deleted the temp file. An optimization could be to save the double I/O cost by using an in-memory buffer to calculate the hash and then write out the buffer to a file once the directory is created. Meanwhile, the copying does seem to work fine for me.

So, after all of this I was able to successfully push a commit with a simple mod to github. Thank you very much for your help. I hope that this discussion has been helpful.

**Comment by driusan** [comment] 2016-12-14 15:43
The driusan/git repo is just a fork of gogits/git which exports StoreObjectLoosely. I can't really comment much on why it does anything internally. I'm trying to get off using the library because it's written at the wrong level of abstraction for writing a git client. (It's too high level to use for plumbing, and if you write the plumbing yourself, then the porcelain should just be built on your own plumbing commands..) The right thing to do is call HashObject with the `-w` option instead of StoreObjectLoosely throughout the code, but HashObject -w isn't implemented yet.

It's definitely worth working around, because the directory already existing is a common case (it doesn't take too long before you end up with two hashes that have the same first byte..) Out of curiousity, what happens if you change it from os.Mkdir to os.MkdirAll? MkdirAll seems to already have a stat check, and is probably more robust anyways: https://golang.org/src/os/path.go?s=488:535#L9

I suspect the reason for the temp/file move is because you don't know the file name until after the entire file is hashed, so it's intended to prevent needing to store the entire file contents + compressed contents in memory, and then writing it out afterwards, but instead directly stream to an io.Writer. I guess there's two options for the rename problem: 1. check the error returned by os.Rename(), and fall back on the copy/move only if there's an error 2. use build tags for OSes that don't let you move between directories and have 2 implementations.

**Comment by sirnewton01** [comment] 2016-12-18 00:47
os.MkdirAll seems to have worked better. I have created a pull request for the git repository with the changes.

**Comment by driusan** [comment] 2016-12-18 01:36
Thanks! I merged it into that repo, so at least it'll work until I've completely weened off of it and reworked everything in terms of plumbing commands.

I'm in the middle of majorish refactoring so hopefully I haven't broken anything else, but since this seems to be resolved I'm closing this issue. If anything else comes up, feel free to open a new one.

**Closed by driusan** 2016-12-18 01:36 UTC
